[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python = ">=3.8.1,<3.10"
deepdog = "^1.0.0"
pdme = "^1.0.0"

[tool.poetry.dev-dependencies]
ipython = "^8.3.0"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
